### ISSUE TITLE
Command line returns Error 410

### ISSUE THREAD

**Issue by domantasdi** [jdpurcell/RechatTool#12]
Hey,

As of today or yesterday, trying to download a chat log returns an `Error: The remote server returned an error: (410) Gone.` error. The VoD is available and returns the same error with any other VoD.

Any chance there were updates on Twitch's side and the tool needs updates?

**Comment by sir-pinecone** [comment]
I'm getting the same error. Something changed on Twitch's end. I might dig into it if I find some time.

**Comment by jdpurcell** [comment]
Yes Twitch removed the API endpoint it was using. I watched a VOD on Twitch's site while monitoring the network requests and found the chat stuff in a URL ending with "/gql" which matches up with the [discussion here](https://github.com/lay295/TwitchDownloader/issues/251). Honestly I don't even use RechatTool myself anymore so I'm not super motivated to fix it, but I might give it a try anyway 😄

**Comment by domantasdi** [comment]
I would greatly appreciate it if you tried to fix it, @jdpurcell ! I've been using the tool for over a year now and it's great!

**Comment by jdpurcell** [comment]
Fixed by [5c615aa](https://github.com/jdpurcell/RechatTool/commit/5c615aabfaa63bc40ebeadf3e6715f3eaef2f99f). New version has been released.

**Comment by sir-pinecone** [comment]
Awesome, thanks!

**Comment by domantasdi** [comment]
Thank you so much, I really appreciate your work!

**Comment by terran244** [comment]
Appreciate you fixing it as I have been using this for several years not and it has been pretty helpful. Apologies if I don't fully understand but what exactly do I do to make it work? I've been using Windows Powershell and I know the usual step is to do ./RechatTool - D and whatever the VOD Id is. Now when I do it, it says I have to download .NET and I have but it's still not working. Am I missing a step? Again sorry if I don't understand

**Comment by jdpurcell** [comment]
@terran244 Did you download the CrossPlatform or Windows zip from the releases? I would recommend the Windows one. It requires .NET Framework 4.6.2 which shouldn't be a problem for most people. As long as Windows Updates have been installed recently and you're not running Windows Vista or older, you shouldn't need to download any .NET runtimes.

**Comment by terran244** [comment]
Okay. I'll reinstall the windows version and see if it works from there
